apiVersion: apps/v1
kind: Deployment

metadata:
  name: analyzer
  namespace: dspm

spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
      - name: analyzer
        image: analyzer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000

