apiVersion: v1
kind: Service

metadata:
  name: analyzer
  namespace: dspm

spec:
  type: ClusterIP  # 내부에서만 접근 가능
  selector:
    app: analyzer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP