apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth
  namespace: dspm

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: comnyang/auth:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3001
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        # Firebase 환경 변수들은 secret이나 configmap으로 관리해야 함
        # 실제 배포시 적절한 secret을 추가해야 함