### AWS Credentials Secret
# Note: 실제 운영에서는 IRSA(IAM Roles for Service Accounts) 사용 권장

apiVersion: v1
kind: Secret

metadata:
  name: aws-credentials
  namespace: dspm

type: Opaque
data:
  # AWS Access Key ID (base64 encoded)
  # 실제 값은 GitHub Secrets에서 설정
  access-key-id: ""
  # AWS Secret Access Key (base64 encoded)  
  # 실제 값은 GitHub Secrets에서 설정
  secret-access-key: ""