# ClusterSecretStore for AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: dspm

---
# ServiceAccount for External Secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: dspm
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::651706765732:role/external-secrets-role

---
# ExternalSecret to sync from AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dspm-rds-secret
  namespace: dspm
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: rds-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: DspmDbSecret74B192CC-oPZpzZJ2fWMz
      property: username
  - secretKey: password
    remoteRef:
      key: DspmDbSecret74B192CC-oPZpzZJ2fWMz
      property: password
  - secretKey: host
    remoteRef:
      key: DspmDbSecret74B192CC-oPZpzZJ2fWMz
      property: host
  - secretKey: port
    remoteRef:
      key: DspmDbSecret74B192CC-oPZpzZJ2fWMz
      property: port
  - secretKey: dbname
    remoteRef:
      key: DspmDbSecret74B192CC-oPZpzZJ2fWMz
      property: dbname