### Ingress (외부 진입점)

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: dspm-ingress 
  namespace: dspm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
  - host: dspm.local
    http:
      paths:
      - path: /collector 
        pathType: Prefix
        backend:
          service:
            name: collector
            port:
              number: 8000
            
      - path: /analyzer
        pathType: Prefix 
        backend:
          service:
            name: analyzer 
            port:
              number: 8000
      
      - path: /dashboard 
        pathType: Prefix 
        backend:
          service:
            name: dashboard
            port:
              number: 8000
      
      - path: /lineage
        pathType: Prefix 
        backend:
          service:
            name: lineage
            port:
              number: 8000