apiVersion: apps/v1
kind: Deployment

metadata:
  name: collector
  namespace: dspm

spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: comnyang/collector:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000

