apiVersion: apps/v1
kind: Deployment

metadata:
  name: collector
  namespace: dspm

spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: comnyang/collector:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        # Analyzer 서비스 연결
        - name: ANALYZER_URL
          value: "http://analyzer:8080"
        - name: API_ENDPOINT
          value: "http://analyzer:8080/api/assets"
        - name: SOURCE_ID
          value: "aws-dspm-production"
        - name: ASSETS_BULK_SIZE
          value: "1000"
        # AWS 설정
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
              optional: true
        # 컬렉터 설정
        - name: COLLECTION_INTERVAL
          value: "300"  # 5분마다 수집
        - name: USE_MOCK
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        - name: RUST_LOG
          value: "info"

